# -*- coding: utf-8 -*-
"""Walmart Sales Forecasting Using SARIMAX with Economic Indicators

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jWjxn0pWrVGjZnD-rkbY13_Zyz5ZoL1-

Install Required Libraries
"""

!pip install statsmodels pmdarima --quiet

"""Import Libraries"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from statsmodels.tsa.statespace.sarimax import SARIMAX
from pmdarima import auto_arima

from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score

import warnings
warnings.filterwarnings('ignore')

"""Load Dataset"""

df = pd.read_csv('Wal-mart sales 2022 - 2025.csv')

df.head()

"""Dataset Information"""

df.shape

df.info()

df.isnull().sum()

"""Convert Date Column"""

df['Date'] = pd.to_datetime(
    df['Date'],
    format='%m/%d/%Y'
)

df.head()

"""Select One Store

For SARIMAX use Store 1.
"""

store1 = df[df['Store'] == 1]

store1.head()

"""Sort by Date"""

store1 = store1.sort_values('Date')

"""Set Date as Index"""

store1.set_index('Date', inplace=True)

store1.head()

"""Plot Weekly Sales"""

plt.figure(figsize=(15,5))

plt.plot(store1['Weekly_Sales'])

plt.title('Store 1 Weekly Sales')

plt.xlabel('Date')
plt.ylabel('Weekly Sales')

plt.show()

"""Define Target Variable (Y)"""

y = store1['Weekly_Sales']

"""Define Exogenous Variables (X)"""

X = store1[
[
    'Holiday_Flag',
    'Temperature',
    'Fuel_Price',
    'CPI',
    'Unemployment'
]
]

"""Train-Test Split (80%-20%)"""

split = int(len(store1)*0.8)

y_train = y[:split]
y_test = y[split:]

X_train = X[:split]
X_test = X[split:]

"""Check Split Size"""

print("Train Size :", len(y_train))
print("Test Size :", len(y_test))

"""Auto ARIMA

Find best parameters automatically.
"""

auto_model = auto_arima(
    y_train,
    exogenous=X_train,
    seasonal=True,
    m=52,
    trace=True,
    suppress_warnings=True,
    stepwise=True
)

print(auto_model.summary())

"""Build SARIMAX Model"""

model = SARIMAX(
    y_train,
    exog=X_train,
    order=(2,0,2),
    seasonal_order=(1,0,0,52)
)

result = model.fit()

print(result.summary())

"""| Variable     | Coefficient | P-value | Result        |
| ------------ | ----------: | ------: | ------------- |
| Holiday_Flag |      104700 |   0.000 | Significant ✅ |
| Temperature  |       -2199 |   0.000 | Significant ✅ |
| Fuel_Price   |       28890 |   0.000 | Significant ✅ |
| CPI          |        7521 |   0.000 | Significant ✅ |
| Unemployment |        -927 |   0.000 | Significant ✅ |

========

| Variable     | Coefficient | Impact on Sales | Business Interpretation                                            |
| ------------ | ----------: | --------------- | ------------------------------------------------------------------ |
| Holiday_Flag |     104,700 | Positive ⬆️     | During holiday weeks, Walmart sales increase significantly.        |
| Temperature  |      -2,199 | Negative ⬇️     | As temperature increases, weekly sales tend to decrease slightly.  |
| Fuel_Price   |      28,890 | Positive ⬆️     | Fuel price changes show a positive relationship with weekly sales. |
| CPI          |       7,521 | Positive ⬆️     | Consumer Price Index (CPI) has a strong influence on sales.        |
| Unemployment |        -927 | Negative ⬇️     | Higher unemployment tends to reduce customer spending and sales.   |
==========

| Variable     | P-Value | Significant? |
| ------------ | ------: | ------------ |
| Holiday_Flag |   0.000 | ✅ Yes        |
| Temperature  |   0.000 | ✅ Yes        |
| Fuel_Price   |   0.000 | ✅ Yes        |
| CPI          |   0.000 | ✅ Yes        |
| Unemployment |   0.000 | ✅ Yes        |

Forecast Test Data
"""

forecast = result.predict(
    start=len(y_train),
    end=len(y)-1,
    exog=X_test
)

forecast.index = y_test.index

"""MAE"""

mae = mean_absolute_error(
    y_test,
    forecast
)

print("MAE :", round(mae,2))

"""RMSE"""

rmse = np.sqrt(
    mean_squared_error(
        y_test,
        forecast
    )
)

print("RMSE :", round(rmse,2))

"""R² Score"""

r2 = r2_score(
    y_test,
    forecast
)

print("R2 Score :", round(r2,4))

"""Actual vs Forecast"""

plt.figure(figsize=(15,5))

plt.plot(
    y_test,
    label='Actual Sales'
)

plt.plot(
    forecast,
    label='Forecast Sales'
)

plt.title('Actual vs Forecast')

plt.xlabel('Date')
plt.ylabel('Weekly Sales')

plt.legend()

plt.show()

"""Create Future Exogenous Variables

Forecast next 12 weeks.
"""

future_exog = pd.DataFrame({
    'Holiday_Flag':[0]*12,
    'Temperature':[X['Temperature'].mean()]*12,
    'Fuel_Price':[X['Fuel_Price'].mean()]*12,
    'CPI':[X['CPI'].mean()]*12,
    'Unemployment':[X['Unemployment'].mean()]*12
})

"""Forecast Next 12 Weeks"""

future_forecast = result.forecast(
    steps=12,
    exog=future_exog
)

future_forecast

"""Display Normal Numbers"""

future_forecast = future_forecast.round(0)

print(future_forecast)

"""Show Future Dates

weekly sales forecasting:
"""

future_dates = pd.date_range(
    start=store1.index[-1],
    periods=13,
    freq='W'
)[1:]

forecast_df = pd.DataFrame({
    'Forecast_Date': future_dates,
    'Forecast_Sales': future_forecast.astype(int)
})

forecast_df

forecast_df.reset_index(drop=True, inplace=True)

forecast_df

"""Forecast result:



| Metric           | Result              |
| ---------------- | ------------------- |
| Forecast Horizon | 12 Weeks            |
| Lowest Forecast  | 1,486,223           |
| Highest Forecast | 1,604,353           |
| Average Forecast | ~1.55 Million       |
| Forecast Period  | Nov 2024 – Jan 2025 |

========

The SARIMAX model predicts that:

Weekly sales will remain between 1.48 million and 1.60 million.
The highest forecasted sales occur around 29-Dec-2024 with approximately 1.60 million sales.
Sales remain relatively stable with normal fluctuations.
Economic indicators (Fuel Price, CPI, Unemployment, Temperature, Holiday Flag) were used to generate these forecasts.

========

Save Forecast to CSV
"""

forecast_df.to_csv(
    'walmart_forecast.csv'
)

forecast_df.head()

plt.figure(figsize=(12,5))

plt.plot(
    forecast_df['Forecast_Date'],
    forecast_df['Forecast_Sales'],
    marker='o'
)

plt.title('Walmart Store 1 - Next 12 Weeks Sales Forecast')
plt.xlabel('Forecast Date')
plt.ylabel('Forecast Sales ($)')

plt.xticks(rotation=45)
plt.grid(True)

plt.show()